import React from 'react';
import { ArrowRight, Pause, Play, SkipForward, ShieldCheck } from 'lucide-react';

export default function DecisionWindow({ analysis, remaining = 0, paused = false, onPause, onResume, onSkip }) {
  const plan = analysis?.bestPlan;
  const evaluation = plan?.evaluation;
  if (!plan || !evaluation) return null;
  const sourceBefore = analysis.sourceLoadBefore ?? 0;
  const sourceAfter = analysis.sourceLoadAfter ?? sourceBefore - evaluation.expectedBenefit;
  const destBefore = analysis.destLoadBefore ?? 0;
  const destAfter = analysis.destLoadAfter ?? destBefore + evaluation.cpuDemand;
  return <div className="rounded-2xl border-2 border-amber-400/60 bg-amber-950/25 p-5 shadow-2xl shadow-amber-950/30 my-4">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-amber-400/20 pb-3"><div><div className="text-[10px] font-mono tracking-widest text-amber-300">MIGRATION ANALYSIS / DECISION PHASE</div><h2 className="text-lg font-bold text-white mt-1">Migration Decision</h2><p className="text-xs text-slate-300 mt-1">ML predicts overload. The Migration Engine is now proving whether moving this process is worthwhile.</p></div><div className="text-center"><div className="text-[10px] text-slate-400 font-mono">STARTS IN</div><div className="text-4xl font-black text-amber-300 font-mono">{Math.ceil(remaining)}s</div><div className="flex gap-1 mt-1"><button onClick={paused ? onResume : onPause} className="px-2 py-1 rounded bg-slate-900 border border-slate-700 text-[10px] text-white flex gap-1 items-center">{paused ? <Play className="w-3 h-3" /> : <Pause className="w-3 h-3" />}{paused ? 'Resume' : 'Pause'}</button><button onClick={onSkip} className="px-2 py-1 rounded bg-cyan-700 text-[10px] text-white flex gap-1 items-center"><SkipForward className="w-3 h-3" /> Skip</button></div></div></div>
    <div className="flex items-center justify-center gap-4 py-4 text-center"><div><div className="text-[10px] text-slate-500">PROCESS</div><div className="text-xl font-bold text-amber-300 font-mono">{plan.process.id}</div></div><div className="text-cyan-300 font-mono">CORE {plan.sourceCoreId} <ArrowRight className="inline w-5 h-5" /> CORE {plan.destCoreId}</div></div>
    <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs font-mono"><div className="rounded-lg bg-slate-950/70 p-3 border border-slate-800"><div className="text-slate-400 mb-2">SOURCE CORE {plan.sourceCoreId}</div><div className="flex justify-between"><span>Current load</span><span className="text-rose-300">{sourceBefore.toFixed(1)}%</span></div><div className="flex justify-between"><span>Expected after</span><span className="text-emerald-300">{sourceAfter.toFixed(1)}%</span></div><div className="text-emerald-300 mt-2">Load reduction: {evaluation.expectedBenefit}%</div></div><div className="rounded-lg bg-slate-950/70 p-3 border border-slate-800"><div className="text-slate-400 mb-2">DESTINATION CORE {plan.destCoreId}</div><div className="flex justify-between"><span>Current load</span><span className="text-cyan-300">{destBefore.toFixed(1)}%</span></div><div className="flex justify-between"><span>Expected after</span><span className="text-cyan-300">{destAfter.toFixed(1)}%</span></div><div className="text-emerald-300 mt-2">Capacity: PASS</div></div><div className="rounded-lg bg-slate-950/70 p-3 border border-slate-800"><div className="text-slate-400 mb-2">TRACEABLE COST</div><div className="flex justify-between"><span>Migration time</span><span>{evaluation.migrationTime}</span></div><div className="flex justify-between"><span>Memory penalty</span><span>{evaluation.memoryPenalty}</span></div><div className="flex justify-between"><span>Cache penalty</span><span>{evaluation.cachePenalty}</span></div><div className="flex justify-between"><span>Security penalty</span><span>{evaluation.securityPenalty}</span></div><div className="border-t border-slate-800 mt-2 pt-2 flex justify-between font-bold"><span>Total cost</span><span className="text-amber-300">{evaluation.migrationCost}</span></div></div></div>
    <div className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-950/70 border border-slate-800 p-3 text-xs font-mono"><div><span className="text-slate-400">Migration score: </span><span className="text-emerald-300">{evaluation.expectedBenefit}</span><span className="text-slate-500"> benefit − </span><span className="text-amber-300">{evaluation.migrationCost}</span><span className="text-slate-500"> cost = </span><strong className="text-cyan-300">+{evaluation.migrationScore}</strong></div><div className="text-emerald-300 flex items-center gap-1"><ShieldCheck className="w-4 h-4" /> SECURITY PASS · MIGRATION APPROVED</div></div>
  </div>;
}
