import React from 'react';
import { Play, Pause, RotateCcw, StepForward, Zap, Sparkles, SkipForward, Settings2 } from 'lucide-react';
import { SCENARIO_MODES } from '../simulation/simulationEngine.js';

export default function SimulationControls({ simTime = 0, status = 'STOPPED', speed = 1, numCores = 4, explanationText = '', mode = SCENARIO_MODES.AUTOMATIC, automaticWorkload = true, decisionDelay = 5, decisionRemaining = 0, onStart, onPause, onResume, onStep, onReset, onGenerateLoad, onRunDemo, onSpeedChange, onNumCoresChange, onModeChange, onAutomaticWorkload, onDecisionDelay, onSkipDecision, onSeedChange, backendHealth }) {
  const isPaused = status === 'PAUSED';
  const isDecision = status === 'DECISION_WINDOW' || (isPaused && decisionRemaining > 0);
  const formatTime = time => `${String(Math.floor(time / 60)).padStart(2, '0')}:${(time % 60).toFixed(1).padStart(4, '0')}`;
  const statusStyle = status === 'MIGRATING' ? 'text-cyan-300 border-cyan-500/40 bg-cyan-500/10' : isDecision ? 'text-amber-300 border-amber-500/40 bg-amber-500/10' : status === 'RUNNING' ? 'text-emerald-300 border-emerald-500/40 bg-emerald-500/10' : 'text-slate-300 border-slate-700 bg-slate-900';
  return <div className="space-y-3 mb-4">
    <div className="glass-panel rounded-xl p-4 border-slate-700">
      <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><span className="text-[10px] text-cyan-400 font-mono tracking-widest">OPERATING SYSTEM SIMULATOR</span><span className="text-[10px] text-slate-500 font-mono">{backendHealth === 'online' ? 'API CONNECTED' : 'LOCAL ML FALLBACK'}</span></div><h1 className="text-xl font-bold text-white font-mono mt-1">MULTICORE CPU SIMULATION</h1></div><div className="flex items-center gap-2 font-mono"><div className="px-3 py-1.5 rounded-lg border border-slate-800 bg-slate-950"><span className="block text-[9px] text-slate-500">CLOCK</span><span className="text-cyan-300 font-bold">{formatTime(simTime)}</span></div><span className={`px-2 py-1 rounded border text-[10px] font-bold ${statusStyle}`}>{status.replace('_', ' ')}</span></div></div>
      <div className="flex flex-wrap items-center justify-between gap-2 mt-4 pt-3 border-t border-slate-800"><div className="flex gap-2 flex-wrap"><button onClick={isPaused ? onResume : onStart} className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs flex items-center gap-1.5">{isPaused ? <Play className="w-4 h-4" /> : <Play className="w-4 h-4 fill-white" />}{isPaused ? 'RESUME' : 'START'}</button><button onClick={onPause} disabled={status === 'STOPPED' || isPaused} className="px-3 py-2 rounded-lg bg-amber-600/90 disabled:opacity-40 text-white font-bold text-xs flex items-center gap-1.5"><Pause className="w-4 h-4" /> PAUSE</button><button onClick={onStep} className="px-3 py-2 rounded-lg bg-slate-800 text-slate-200 border border-slate-700 text-xs flex items-center gap-1.5"><StepForward className="w-4 h-4" /> STEP</button><button onClick={onReset} className="px-3 py-2 rounded-lg bg-slate-800 text-slate-300 border border-slate-700 text-xs flex items-center gap-1.5"><RotateCcw className="w-4 h-4" /> RESET</button>{isDecision && <button onClick={onSkipDecision} className="px-3 py-2 rounded-lg bg-cyan-700 text-white font-bold text-xs flex items-center gap-1.5"><SkipForward className="w-4 h-4" /> SKIP DELAY</button>}</div><div className="flex gap-2"><button onClick={() => onGenerateLoad?.()} className="px-3.5 py-2 rounded-lg bg-gradient-to-r from-orange-600 to-red-600 text-white font-bold text-xs flex items-center gap-1.5"><Zap className="w-4 h-4" /> INJECT LOAD</button><button onClick={onRunDemo} className="px-3.5 py-2 rounded-lg bg-gradient-to-r from-cyan-600 to-blue-600 text-white font-bold text-xs flex items-center gap-1.5"><Sparkles className="w-4 h-4" /> GUIDED DEMO</button></div></div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-3 text-xs"><div className="p-3 rounded-lg bg-slate-950 border border-slate-800"><div className="text-[10px] text-slate-500 font-mono mb-2">SIMULATION MODE</div><select value={mode} onChange={e => onModeChange?.(e.target.value)} className="w-full bg-slate-900 border border-slate-700 rounded px-2 py-1.5 text-slate-200"><option value={SCENARIO_MODES.AUTOMATIC}>Automatic Simulation</option><option value={SCENARIO_MODES.GUIDED}>Guided Demo</option><option value={SCENARIO_MODES.MANUAL}>Manual Demo</option></select><label className="flex gap-2 items-center mt-2 text-slate-300"><input type="checkbox" checked={automaticWorkload} onChange={e => onAutomaticWorkload?.(e.target.checked)} /> Automatic Workload</label></div><div className="p-3 rounded-lg bg-slate-950 border border-slate-800"><div className="text-[10px] text-slate-500 font-mono mb-2 flex gap-1 items-center"><Settings2 className="w-3 h-3" /> DECISION WINDOW</div><label className="flex justify-between text-slate-300">Delay <span className="text-amber-300 font-mono">{decisionDelay}s</span></label><input type="range" min="1" max="10" step="1" value={decisionDelay} onChange={e => onDecisionDelay?.(e.target.value)} className="w-full accent-amber-400" />{isDecision && <div className="text-amber-300 font-mono mt-1">Migration starts in {Math.ceil(decisionRemaining)}s</div>}</div><div className="p-3 rounded-lg bg-slate-950 border border-slate-800"><div className="text-[10px] text-slate-500 font-mono mb-2">CPU / CLOCK SPEED</div><div className="flex gap-1 mb-2">{[4, 6, 8].map(coreCount => <button key={coreCount} onClick={() => onNumCoresChange?.(coreCount)} className={`px-2 py-1 rounded border text-[10px] ${numCores === coreCount ? 'text-cyan-200 border-cyan-400 bg-cyan-500/20' : 'text-slate-400 border-slate-700'}`}>{coreCount} cores</button>)}{[0.5, 1, 2, 4].map(value => <button key={value} onClick={() => onSpeedChange?.(value)} className={`px-2 py-1 rounded border text-[10px] ${speed === value ? 'text-purple-200 border-purple-400 bg-purple-500/20' : 'text-slate-400 border-slate-700'}`}>{value}x</button>)}</div><label className="text-[10px] text-slate-500">Seed <input type="number" defaultValue="42" onChange={e => onSeedChange?.(e.target.value)} className="ml-2 w-20 bg-slate-900 border border-slate-700 rounded px-1 py-0.5 text-slate-200" /></label></div></div>
    </div>
    <div className="glass-panel rounded-xl p-3 border-indigo-500/30 bg-indigo-950/20"><div className="text-[10px] text-indigo-300 font-mono mb-1">SYSTEM EXPLANATION</div><p className="text-xs text-slate-200">{explanationText}</p></div>
  </div>;
}
